### ISSUE TITLE
Widget in popup

### ISSUE THREAD

**Issue by andreazanini** [lara-zeus/popover#12]
It would be really great to have a widget or filament component in the popup, having the same strcture for the popup too.

like to do ->content(Infolist::make()->schema([TextEntry::make( ... and so on

Is it possible?

**Comment by atmonshi** [comment]
ya it should be possible:
https://larazeus.com/docs/popover/v1/getting-started/installation#content-use-it-in-your-infolist

please test and let me know

**Comment by andreazanini** [comment]
wow sorry my bad i didn't understand how to use it. SUPER!
