### ISSUE TITLE
Broken on tables at latest filament

### ISSUE THREAD

**Issue by dbpolito** [lara-zeus/popover#14]
Hey man, love your work...

But it seems popover got broken on latest version, because of this PR:

https://github.com/filamentphp/filament/pull/11524

![image](https://github.com/lara-zeus/popover/assets/347400/34c5d7fa-14e8-4dbc-a695-788ab895158c)

Not sure it will be a good way of making it work besides reverting this on filament, for now i reverted the filament upgrade...

**Comment by atmonshi** [comment]
thanks for the report, can you test this pr #15  if it worked?

**Comment by dbpolito** [comment]
It's definitely looking better, but lost the ability for placement and offset:

before
![image](https://github.com/lara-zeus/popover/assets/347400/6aa03601-4d4f-4d07-8d30-6e83d7c383e9)

after
![image](https://github.com/lara-zeus/popover/assets/347400/f78a17b8-a920-43a6-8e01-28c42e1dec63)

I left a comment on PR too, i think it should be simple to fix

**Comment by atmonshi** [comment]
prefect will work on it tomorrow and release a new version

**Comment by atmonshi** [comment]
sorry for the delay, [all done](https://github.com/lara-zeus/popover/releases/tag/1.1.3)

**Comment by dbpolito** [comment]
thanks! ❤️
