### ISSUE TITLE
Missing state editing

### ISSUE THREAD

**Issue by andreazanini** [lara-zeus/popover#16]
Hello again,
i need to show the sum of some prices in the table and I would like with the popover to show a detail like a small cart.
I have multiple values and can sum properly with normal TextColumn by using formatStateUsing...
but when I use it with your package it says

Method LaraZeus\Popover\Tables\PopoverColumn::formatStateUsing does not exist.

So how can I do something similar?
Thanks

**Comment by atmonshi** [comment]
I'll see if its possible to support `formatStateUsing` but since you already have to use `->content()` and you can pass the record, dont see a reason for `formatStateUsing `!

**Comment by andreazanini** [comment]
But i say about the tablet value, not the popup that i already set.


________________________________

**Comment by atmonshi** [comment]
ah I got you, can you test this branch see if it working
https://github.com/lara-zeus/popover/pull/17

**Comment by atmonshi** [comment]
you can update now to last [version](https://github.com/lara-zeus/popover/releases/tag/1.1.4)

**Comment by andreazanini** [comment]
Thank you boss❤️


Zanini Andrea

Selettronica S.a.s.

via A.della Scala 74/76  37017 Lazise (VR)

Tel. 045. 575858

Fax. 045.575111

http://www.selettronica.it<http://www.selettronica.it/>

________________________________

**Comment by andreazanini** [comment]
Hello, sorry to say that but it seems to not be working correctly

If i put like this the title is not changed

```
 PopoverColumn::make('utente.name')
                    // most of filament methods will work
                    //->sortable()
                    ->prefix('€ ')->formatStateUsing(fn (string $state) => "example")
                    ->label('Totale')
```

while doing this correctly puts "example" as text in the view

```
TextColumn::make('utente.name')
                    ->sortable()->formatStateUsing(fn (string $state) => "example"),

```

**Comment by andreazanini** [comment]
I created pull request #18 that fixes on my side, feel free to check and edit
