### ISSUE TITLE
Different font size than the default table columns

### ISSUE THREAD

**Issue by neamtua** [lara-zeus/popover#19]
Hi,
It seems like the popover columns have larger text than the table default in filament v3. Any way to change that?

![CleanShot 2024-05-27 at 12 20 53@2x](https://github.com/lara-zeus/popover/assets/1029457/e7cc024f-69b4-43b1-8920-bd60f0ce1164)

**Comment by atmonshi** [comment]
you can publish the view to customize it or submit a PR to use the same classes as filament default text
