### ISSUE TITLE
livewire uncaught component not found

### ISSUE THREAD

**Issue by elfeffe** [lara-zeus/popover#5]
I'm getting that error when I use a Livewire component.
I have tried with wire:key, but it still doesn't work.
Any idea?

**Comment by atmonshi** [comment]
this is in the console right?
ya I was getting this too but didn't found any fix for it unfortunately.

**Comment by atmonshi** [comment]
hey @elfeffe can you test the branch `refactor-to-anchor` 
I did swipe tooltip with alpine x-anchor, see if this solve the issue!

**Comment by elfeffe** [comment]
With that branch I have this new error "Uncaught Snapshot missing on Livewire component with id: MqILLfiLO5PRLOVEJxoP".
But at least the rest of the Livewire functionalities work.
With the master branch they don't work after the error.

**Comment by atmonshi** [comment]
ok hopefully this time it fixed
pull the new changes in the same branch.
and inside popover, make sure to add `key()`

```html
<div>
    @livewire(\App\Livewire\UserCard::class, ['lazy' => true], key("something-{$record->id}"))
</div>
```

let me know how it goes

**Comment by elfeffe** [comment]
No :(
It seems to try to initialize the livewire component on every hover event. And I think the problem is related to that.

**Comment by atmonshi** [comment]
hey, I have news, one good and one bad, will, ish... 😂

the issue was fixed before and from the plugin, I cant do anything else..
but there is a fix you can do:

you must add a unique key as the example:

in your form:
please notice the `type` is our key per column

```php
PopoverColumn::make('name')
    //.... other config
    ->content(fn ($record) => view('filament.user-card', ['record' => $record, 'type' => 'name'])),

PopoverColumn::make('email')
    //.... other config
    ->content(fn ($record) => view('filament.user-card', ['record' => $record, 'type' => 'email'])),
```

now in your LW view:

```html
<livewire:user-card :$record :key="$record->id.'-'.$type"/>
```
this way every popover in the same row will have a unique key

I did release new version, please test and let me know

https://github.com/lara-zeus/popover/releases/tag/1.1.0

**Comment by atmonshi** [comment]
I also updated the demo
https://demo.larazeus.com/admin/components-demo/popover

**Comment by atmonshi** [comment]
feel free to create another issue if you faced more issues :)

**Comment by elfeffe** [comment]
Thank you, I was working in a different project and didn't have time to test it.
