### ISSUE TITLE
hover trigger

### ISSUE THREAD

**Issue by danpalmieri** [lara-zeus/popover#9]
I just added:
```js
@pointerenter="$time = setTimeout(() => { open = true }, 200)"
@pointerleave="clearTimeout($time); open = false"
```
and it worked...

I'm missing something? Can we add hover support?

**Comment by atmonshi** [comment]
yes it should be fine, I commented it out when moved from tippy to alpine anchor to do more tests
I will work on it today and make sure all the options available for hover :)
